### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by Freeaqingme** [juli4n/rsync#4]
The headers of each file refer to a BSD-style license, referring to the LICENSE file. That file is however rather conspicuous by its absence. Could you may add the file, or stipulate under what exact terms this repo can be used?

Nonetheless, thanks for this project. Really useful :)

**Comment by juli4n** [comment]
That's funny. I probably forgot to add the license file. I originally wrote this code just for fun, trying to understand how the rsync algorithm works.
I see some people forking / using it so it might be good time to add a proper license to it.
Would an apache 2.0 style license work for you? 
I don't have much time to work on this these days, but I'll appreciate a PR fixing this.
Thanks!

**Comment by Freeaqingme** [comment]
Apache 2.0 would work marvellously well. I'll submit a pr in a few days to add it.

**Comment by Freeaqingme** [comment]
This is covered in #7
