### ISSUE TITLE
State of branch 'readers'?

### ISSUE THREAD

**Issue by Freeaqingme** [juli4n/rsync#5]
I stumbled on the branch 'readers'. It seems quite complete and neat. I realize it's been a while that you probably worked on this project, but do you remember if there's any reason why it's not merged to master?

Maybe that was never the intention, but if there are any bugs or other concerns that you had I'd be happy to hear about them (and potentially fix them) before putting it into production :)

Thanks!

**Comment by juli4n** [comment]
Hey Dolf, sorry for the late response! I'm glad you found this useful. 
Honestly, I haven't had time to test it properly (it was just the result of a single pass) but I'll certainly appreciate if you want to take and send a PR.  As you said, it should be pretty close.

**Comment by Freeaqingme** [comment]
> As you said, it should be pretty close.

Yeah, except for the CalculateDifferences(). That was a fun one to fix :)

Covered in PR #7 .
